
services:
  # Nginx Streaming Server
  nginx-stream:
    image: webrtc_prometheus  # Imagen creada
    container_name: webrtc_prometheus # nombre único de la magen creada
    ports:   # puertos necesarios para la configuración del servidor
      - "1935:1935" # puerto de streaming a configurar en OBS studio.
      - "80:80"     # puerto para la página donde se aloja el streaming
      - "443:443"   # puerto https
    volumes:
    # volúmenes para el nginx y los certificados
    - ../nginx.conf:/usr/local/nginx/conf/nginx.conf
    - ../certs:/usr/local/nginx/certs
    restart: unless-stopped
    networks:
      - streaming_network # Red para el streaming
      # - monitoring_network # Optconal: para otras configuraciones de Prometheus

  # Nginx Prometheus Exporter
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_prometheus_exporter
    ports:
      - "9113:9113"
    environment:
      # 'nginx-stream' ha de ser el nombre del servicio en este fichero. Ambos servicios deben estar en la misma red.
      NGINX_STUB_STATUS_URL: http://nginx-stream:80/nginx_status
    restart: unless-stopped
    networks:
      - monitoring_network


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_server
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle
    restart: unless-stopped
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_server
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=prom_admin
    restart: unless-stopped
    networks:
      - monitoring_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter_server
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro'
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - monitoring_network

networks:
  # Define both networks
  streaming_network:
    driver: bridge
  monitoring_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: